(refactor): Update new functionalities in Flourish Child App
flourishbhp/flourish-child pull request #344
Opened 2024-05-24 08:09 UTC by nmunatsibw

This commit includes updates in `apps.py`, `model_mixins.py`, `forms` files, and test files in the Flourish Child App. Changes are made to the `reason_field` in `EdcMetadataAppConfig` and reordering of import statements in `mommy_recipes.py`. In the `HIVTestingAndResultingMixin` class, a new condition has been added to the save function to accommodate unscheduled appointments. In several form classes in `infant_hiv_testing_form.py`, `SubjectModelFormMixin` was replaced by `ChildModelFormMixin`. Start of implementation of test scenarios for Infant HIV testing was also included. Signed-off-by: nmunatsibw

2024-05-27 09:25 UTC, amediphoko requested changes

2024-05-27 09:25 UTC, amediphoko commented on flourish_child/models/model_mixins/hiv_testing_and_resulting_mixin.py
> +            obj, _ = Appointment.objects.get_or_create(
There's already an appointment creator that validates appointments created, why are you not using it?

2024-05-27 09:34 UTC, nmunatsibw commented on flourish_child/models/model_mixins/hiv_testing_and_resulting_mixin.py
> +            obj, _ = Appointment.objects.get_or_create(
because i didnt know about it

2024-05-28 07:21 UTC, amediphoko requested changes

2024-05-28 07:21 UTC, amediphoko commented on flourish_child/models/model_mixins/hiv_testing_and_resulting_mixin.py
> +            appointment_creator = UnscheduledAppointmentCreator(
Proper error handling ?

2024-05-30 07:56 UTC, amediphoko approved these changes

2024-05-30 07:56 UTC, merged